version: "3.7"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  accounts:
    build: ./accounts
  api:
    build: ./api
    depends_on:
      - nginx-proxy
      - accounts
      - products
  products:
    build: ./products
