version: "3.7"
services:
  api:
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: api.local
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
